### ISSUE TITLE
Friends Tab not Transparent 

### ISSUE THREAD

**Issue by NeptuneRemix** [Ruben7173/Ruben7173.github.io#3]
The Friends tab has reverted back to the base discord color and completely covers the background image whereas before it was transparent
Caused by an update with discord i believe
![image](https://user-images.githubusercontent.com/46643635/51083184-5dde2800-16db-11e9-9cd8-88586e429ed6.png)

**Comment by Malitahj** [comment]
This. Friends and Library/Inventory.

**Comment by Ruben7173** [comment]
Fixed
