### ISSUE TITLE
Darling in the FranXX theme breaking

### ISSUE THREAD

**Issue by Whovian9369** [Ruben7173/Ruben7173.github.io#6]
Hello! I use the Zero Two theme on BetterDiscord a lot, so than you!

However, the theme background broke recently. The issue seems to be that you're using the "Development URL" from GitHack instead of the "Production URL" for the following line (Line 3 in 02-theme.theme.css)
`@import url(https://raw.githack.com/Ruben7173/Ruben7173.github.io/master/BetterDiscord-Themes/Darling-in-The-Franxx/code.css);`

After some local testing with both URLs, the Dev URL gives me a black background in BetterDiscord while Production URL gives me the expected background. Only issues that I can see with this change is that you'd have to update the URL each time in 02-theme.theme.css and hope the user checks the repository. 

However, I just realized, that the blue-space theme that's also in this repository seems to work perfectly with what appears to be the Dev URL, so I'm not sure what the issue is there (WAY More people using the 02 theme than blue-space?) but I can only give my personal experience.

Thanks for your time.

**Comment by Ruben7173** [comment]
Ill update the url to dev url
